Desktop/Project3/config/routes.rb
Project3::Application.routes.draw do
  match 'generic' => 'pages#index'

  match 'baby' => 'pages#baby'

  match 'birthday' => 'pages#birthday'

  match 'graduation' => 'pages#graduation'

  match 'Babyshower/home.html', :to => redirect('/index.html')

  match 'Graduation/home.html', :to => redirect('/index.html')

  match 'Birthday/home.html', :to => redirect('/index.html')

    match 'Charity/home.html', :to => redirect('/index.html')

  root :to => 'pages#index'

end

Desktop/Project3/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @stylesheet = "generic.css.scss"
  end

  def baby
    @stylesheet = "baby.css.scss"
  end

  def birthday
    @stylesheet = "birthday.css.scss"
  end

  def graduation
    @stylesheet = "graduation.css.scss"
  end

end

Desktop/Project3/app/helpers/application_helper.rb
module ApplicationHelper
  def stylesheet_selection
    if @stylesheet.nil?
      application
    else
      @stylesheet
    end
  end
  
end

Desktop/Project3/app/helpers/pages_helper.rb
module PagesHelper
end

Desktop/Project3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project3</title>
  <%= stylesheet_link_tag "application" %>
  <%= stylesheet_link_tag stylesheet_selection %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Project 3</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Baby Shower", baby_path%></li>
          <li><%= link_to "Birthday", birthday_path %></li>
          <li><%= link_to "Graduation", graduation_path %></li>
          <li><%= link_to "Generic", generic_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

  <%= yield %>


</body>
</html>

Desktop/Project3/app/views/pages/baby.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Arrangement   by Free CSS Templates</title>
<link href="style.css" rel="stylesheet" type="text/css" media="screen" />
</head>
<body>
<div id="wrapper">
	<div id="header">
		<div id="logo">
			<h1><a href="#">Baby shower</a></h1>
		</div>
		
	</div>
	<div id="menu">
		<ul>
			<li class="current_page_item"><span><a href="#">Home</a></span></li>
			<li><a href="#">About babies</a></li>
			<li><a href="#">Our story</a></li>
			<li><a href="#">Gift list</a></li>

		</ul>
	</div>
	<!-- end #menu -->
	
	<!-- end #header -->
	<div id="page">
		<div id="content">
			<div class="post">
				<h2 class="title"><a href="#">Welcome to the baby shower </a></h2>
				
				<div class="entry">
					<p><img src="images/pic1.jpg" width="540" height="300" alt="" /></p>
					<p>Bottles and booties 
and bibs and more, 
let's shower the baby 
with gifts galore! 
Please come to a baby shower for 
Sally and Michael Kent 
Given by Lauren, Katherine, and Mandy Kent .</p>
					<p><a href="#" class="links">Full Details</a></p>
				</div>
			</div>
			
			
			<div style="clear: both;">&nbsp;</div>
		</div>
		
		<div id="sidebar">
			<ul>
				
				<li>
					<h2>All you need to know</h2>
					<ul>
						<li><a href="#">The location</a></li>
						<li><a href="#">The map</a></li>
						<li><a href="#">The date</a></li>
						<li><a href="#">Registration</a></li>
						<li><a href="#">Food served</a></li>
						<li><a href="#">Suggestions</a></li>
					</ul>
				</li>
			</ul>
		</div>
		
		<div style="clear: both;">&nbsp;</div>
	</div>

</div>
<div id="footer-wrapper">
	
	>
</div>
<div id="footer">
	<p>if you have any questions please call us on:974)66456342</p>
</div>
</body>
</html>

Desktop/Project3/app/views/pages/birthday.html.erb
 <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Let's party</title>
<link href="style.css" rel="stylesheet" type="text/css" media="screen" />
</head>
<body>
<div id="wrapper">
	<div id="header">
		<div id="menu">
			<ul>
				<li class="first current_page_item"><a href="#">Home</a></li>
				<li><a href="#">When</a></li>
				<li><a href="#">Where</a></li>
				<li><a href="#">Map</a></li>
				<li><a href="#">Theme</a></li>
				<li><a href="#">Guests</a></li>
			</ul>
		</div>
		<div id="logo">
			<h1><a href="#">Let's party </a></h1>
			<p> Like never before </p>
            <p><img src="images/p.jpg" width="540" height="260" alt="" 
                    style="margin-left: 0px; margin-top: 18px" /></p>
		</div>
	</div>
	
	
	<div id="page">
		<div id="page-bgtop">
			<div id="page-bgbtm">
				
				
				<div id="sidebar">
					<ul>
						<li>
							<h2>Games we are going to play in my birthday</h2>
							<ul>
								<li><a href="#">Candy game</a></li>
								<li><a href="#">Who am'I</a></li>
								<li><a href="#">Guess the number</a></li>
								<li><a href="#">Animal acting</a></li>
								<li><a href="#">Balloon game</a></li>
								<li><a href="#">Clue game</a></li>
							</ul>
						</li>
						
						
					</ul>
				</div>
				
				
			</div>
		</div>
	</div>
	<br /><br /><br /><br /><br /><br /><br /><br /><br /><br />


</div>

</body>
</html>

Desktop/Project3/app/views/pages/graduation.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title> Graduation Party </title>
<link href="style.css" rel="stylesheet" type="text/css" media="screen" />
<script type="text/javascript" src="jquery-1.6.2.min.js"></script>
<script type="text/javascript" src="jquery.poptrox-0.1.js"></script>
</head>
<body>
<div id="header" class="container">
	<div id="logo">
		<h1><a href="#">Graduation </a>
		Party </h1>
		
	</div>
	<div id="menu">
		<ul>
			<li class="current_page_item"><a href="#">Homepage</a></li>
			<li><a href="#">Location</a></li>
			<li><a href="#">Fix the date</a></li>
			<li><a href="#">Theme</a></li>
			<li><a href="#">Contact us</a></li>
		</ul>
	</div>
</div>

<div id="images">
	
	<ul id="gallery">
		<li><img src="images/g.jpg" title="image." alt="" /></li>
		<li><img src="images/g1.jpg" title="image1." alt="" /></li>
		<li><img src="images/g2.jpg" title="image2." alt="" /></a></li>
		<li><img src="images/g3.jpg" title="image3." alt="" /></li>
		<li><img src="images/g4.jpg" title="imag4." alt="" /></li>
		<li><img src="images/g5.jpg" title="image5." alt="" /></li>
	
		
	</ul>
	

</div>
<div id="page">
	<div id="bg1">
		<div id="bg2">
			<div id="bg3">
				<div id="content">
					<h2>About the party</h2>
					<p> Fatma and Arif are graduating from high school this year and the Al Doha family is planning a major party to celebrate this milestone. Mrs. Al Doha had thought about mailing invitations, but Mr. Al Doha realizes that it would be more efficient to handle the entire invitation/RSVP process online. </p>
					<h2>Your are invited!</h2>
					<p>You are cordially invited to
                       Rock Around the Clock
                       at King High School
                       Class of 2018
                       25th Reunion Celebration
                       on June 12, 2018
                       at 3:00 p.m.
                       Dinner and 50's Dance will follow
                       Sandpepper Clubhouse
                       4580 Main Street
                       Austin, Texas. </p>
                       <h2>Register now</h2>
                      kindly email us you name and your coordination on register@htomail.com 

				</div>
			</div>
		</div>
	</div>
</div>
<div id="footer">
	<p>Please if you have any questions contact us on Mr.AlDoha@hotmail.com</a>.</p>
</div>
</body>
</html>

Desktop/Project3/app/views/pages/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Charity Pary</title>
<link href="style.css" rel="stylesheet" type="text/css" media="screen" />
</head>
<body>
<div id="wrapper">
	<div id="page">
		<div id="page-bgtop">
			<div id="page-bgbtm">
				<div id="content">
					<div class="post">
						<h2 class="title"><a href="#">Welcome to out charity party </a></h2>
						
						
						<div class="entry">
							<p <br /> We judge ourselves by our ability to make a difference.<br />Not noisily or with sanctimonious complacency, <br />but deep inside, in that still small place where we really talk to ourselves.” <br />– Stephen Fry </p>
							<p class="links"><a href="#">Read More</a> <br /><a href="#">Comments</a></p>
						</div>
					</div>
					
					
					
					<div style="clear: both;">&nbsp;</div>
				</div>
			
				<div id="sidebar">
					<div id="logo">
						<h1><a href="#">Charity Party </a></h1>
						<p>Because they need us</p>
					</div>
					<div id="menu">
						<ul>
							<li class="current_page_item"><a href="#">Home</a></li>
							<li><a href="#">Blog</a></li>
							<li><a href="#">Photos</a></li>
							<li><a href="#">About</a></li>
							<li><a href="#">Links</a></li>
							<li><a href="#">Contact us</a></li>
						</ul>
					</div>
					
				</div>
				
				<div style="clear: both;">&nbsp;</div>
			</div>
		</div>
	</div>
	
</div>
<div id="footer">
	<p>Save the world.</p>
</div>

</body>
</html>